[project]
name = "analiser-cocomo2"
version = "0.1.0"
description = "Analisador de código baseado em COCOMO II"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=13.7.0",
    "pathspec>=0.12.1",
]
